// Code generated by MockGen. DO NOT EDIT.
// Source: list.go

// Package mposition is a generated GoMock package.
package mposition

import (
	exchange "cf_arbitrage/exchange"
	position "cf_arbitrage/logic/position"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockList is a mock of List interface.
type MockList struct {
	ctrl     *gomock.Controller
	recorder *MockListMockRecorder
}

// MockListMockRecorder is the mock recorder for MockList.
type MockListMockRecorder struct {
	mock *MockList
}

// NewMockList creates a new mock instance.
func NewMockList(ctrl *gomock.Controller) *MockList {
	mock := &MockList{ctrl: ctrl}
	mock.recorder = &MockListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockList) EXPECT() *MockListMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockList) Close(ctx context.Context, spotC exchange.Client, swapC exchange.SwapClient, crClose float64, loseTradeUnit int, totalLimit float64, spot, swap *exchange.Depth) (*position.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, spotC, swapC, crClose, loseTradeUnit, totalLimit, spot, swap)
	ret0, _ := ret[0].(*position.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close.
func (mr *MockListMockRecorder) Close(ctx, spotC, swapC, crClose, loseTradeUnit, totalLimit, spot, swap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockList)(nil).Close), ctx, spotC, swapC, crClose, loseTradeUnit, totalLimit, spot, swap)
}

// Open mocks base method.
func (m *MockList) Open(ctx context.Context, spotC exchange.Client, swapC exchange.SwapClient, srOpen float64, openTradeUnit int, spot, swap *exchange.Depth) (*position.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, spotC, swapC, srOpen, openTradeUnit, spot, swap)
	ret0, _ := ret[0].(*position.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockListMockRecorder) Open(ctx, spotC, swapC, srOpen, openTradeUnit, spot, swap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockList)(nil).Open), ctx, spotC, swapC, srOpen, openTradeUnit, spot, swap)
}

// Position mocks base method.
func (m *MockList) Position() *position.PositionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Position")
	ret0, _ := ret[0].(*position.PositionInfo)
	return ret0
}

// Position indicates an expected call of Position.
func (mr *MockListMockRecorder) Position() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Position", reflect.TypeOf((*MockList)(nil).Position))
}

// UpdateAccount mocks base method.
func (m *MockList) UpdateAccount(ctx context.Context, spotC exchange.Client, swapC exchange.SwapClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, spotC, swapC)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockListMockRecorder) UpdateAccount(ctx, spotC, swapC interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockList)(nil).UpdateAccount), ctx, spotC, swapC)
}
