// Code generated by MockGen. DO NOT EDIT.
// Source: ../../exchange/client.go

// Package mexchange is a generated GoMock package.
package mexchange

import (
	exchange "cf_arbitrage/exchange"
	context "context"
	reflect "reflect"

	exchange0 "github.com/NadiaSama/ccexgo/exchange"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Depth mocks base method.
func (m *MockClient) Depth() <-chan *exchange.Depth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Depth")
	ret0, _ := ret[0].(<-chan *exchange.Depth)
	return ret0
}

// Depth indicates an expected call of Depth.
func (mr *MockClientMockRecorder) Depth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Depth", reflect.TypeOf((*MockClient)(nil).Depth))
}

// Done mocks base method.
func (m *MockClient) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockClientMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockClient)(nil).Done))
}

// Error mocks base method.
func (m *MockClient) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockClientMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockClient)(nil).Error))
}

// FeeRate mocks base method.
func (m *MockClient) FeeRate() exchange.FeeRate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeRate")
	ret0, _ := ret[0].(exchange.FeeRate)
	return ret0
}

// FeeRate indicates an expected call of FeeRate.
func (mr *MockClientMockRecorder) FeeRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeRate", reflect.TypeOf((*MockClient)(nil).FeeRate))
}

// FetchBalance mocks base method.
func (m *MockClient) FetchBalance(ctx context.Context) ([]exchange0.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBalance", ctx)
	ret0, _ := ret[0].([]exchange0.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBalance indicates an expected call of FetchBalance.
func (mr *MockClientMockRecorder) FetchBalance(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBalance", reflect.TypeOf((*MockClient)(nil).FetchBalance), ctx)
}

// FetchOrder mocks base method.
func (m *MockClient) FetchOrder(ctx context.Context, order *exchange0.Order) (*exchange0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOrder", ctx, order)
	ret0, _ := ret[0].(*exchange0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOrder indicates an expected call of FetchOrder.
func (mr *MockClientMockRecorder) FetchOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrder", reflect.TypeOf((*MockClient)(nil).FetchOrder), ctx, order)
}

// MarketOrder mocks base method.
func (m *MockClient) MarketOrder(ctx context.Context, side exchange0.OrderSide, amount decimal.Decimal) (*exchange0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarketOrder", ctx, side, amount)
	ret0, _ := ret[0].(*exchange0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarketOrder indicates an expected call of MarketOrder.
func (mr *MockClientMockRecorder) MarketOrder(ctx, side, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarketOrder", reflect.TypeOf((*MockClient)(nil).MarketOrder), ctx, side, amount)
}

// MockSwapClient is a mock of SwapClient interface.
type MockSwapClient struct {
	ctrl     *gomock.Controller
	recorder *MockSwapClientMockRecorder
}

// MockSwapClientMockRecorder is the mock recorder for MockSwapClient.
type MockSwapClientMockRecorder struct {
	mock *MockSwapClient
}

// NewMockSwapClient creates a new mock instance.
func NewMockSwapClient(ctrl *gomock.Controller) *MockSwapClient {
	mock := &MockSwapClient{ctrl: ctrl}
	mock.recorder = &MockSwapClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSwapClient) EXPECT() *MockSwapClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSwapClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSwapClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSwapClient)(nil).Close))
}

// Depth mocks base method.
func (m *MockSwapClient) Depth() <-chan *exchange.Depth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Depth")
	ret0, _ := ret[0].(<-chan *exchange.Depth)
	return ret0
}

// Depth indicates an expected call of Depth.
func (mr *MockSwapClientMockRecorder) Depth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Depth", reflect.TypeOf((*MockSwapClient)(nil).Depth))
}

// Done mocks base method.
func (m *MockSwapClient) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockSwapClientMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockSwapClient)(nil).Done))
}

// Error mocks base method.
func (m *MockSwapClient) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockSwapClientMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockSwapClient)(nil).Error))
}

// FeeRate mocks base method.
func (m *MockSwapClient) FeeRate() exchange.FeeRate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeRate")
	ret0, _ := ret[0].(exchange.FeeRate)
	return ret0
}

// FeeRate indicates an expected call of FeeRate.
func (mr *MockSwapClientMockRecorder) FeeRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeRate", reflect.TypeOf((*MockSwapClient)(nil).FeeRate))
}

// FetchBalance mocks base method.
func (m *MockSwapClient) FetchBalance(ctx context.Context) ([]exchange0.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBalance", ctx)
	ret0, _ := ret[0].([]exchange0.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBalance indicates an expected call of FetchBalance.
func (mr *MockSwapClientMockRecorder) FetchBalance(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBalance", reflect.TypeOf((*MockSwapClient)(nil).FetchBalance), ctx)
}

// FetchOrder mocks base method.
func (m *MockSwapClient) FetchOrder(ctx context.Context, order *exchange0.Order) (*exchange0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOrder", ctx, order)
	ret0, _ := ret[0].(*exchange0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOrder indicates an expected call of FetchOrder.
func (mr *MockSwapClientMockRecorder) FetchOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrder", reflect.TypeOf((*MockSwapClient)(nil).FetchOrder), ctx, order)
}

// Funding mocks base method.
func (m *MockSwapClient) Funding(ctx context.Context) ([]exchange0.Finance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Funding", ctx)
	ret0, _ := ret[0].([]exchange0.Finance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Funding indicates an expected call of Funding.
func (mr *MockSwapClientMockRecorder) Funding(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Funding", reflect.TypeOf((*MockSwapClient)(nil).Funding), ctx)
}

// FundingRate mocks base method.
func (m *MockSwapClient) FundingRate(ctx context.Context) (*exchange0.FundingRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FundingRate", ctx)
	ret0, _ := ret[0].(*exchange0.FundingRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FundingRate indicates an expected call of FundingRate.
func (mr *MockSwapClientMockRecorder) FundingRate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FundingRate", reflect.TypeOf((*MockSwapClient)(nil).FundingRate), ctx)
}

// MarketOrder mocks base method.
func (m *MockSwapClient) MarketOrder(ctx context.Context, side exchange0.OrderSide, amount decimal.Decimal) (*exchange0.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarketOrder", ctx, side, amount)
	ret0, _ := ret[0].(*exchange0.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarketOrder indicates an expected call of MarketOrder.
func (mr *MockSwapClientMockRecorder) MarketOrder(ctx, side, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarketOrder", reflect.TypeOf((*MockSwapClient)(nil).MarketOrder), ctx, side, amount)
}

// Position mocks base method.
func (m *MockSwapClient) Position(ctx context.Context) (*exchange0.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Position", ctx)
	ret0, _ := ret[0].(*exchange0.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Position indicates an expected call of Position.
func (mr *MockSwapClientMockRecorder) Position(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Position", reflect.TypeOf((*MockSwapClient)(nil).Position), ctx)
}

// MockFundTransfer is a mock of FundTransfer interface.
type MockFundTransfer struct {
	ctrl     *gomock.Controller
	recorder *MockFundTransferMockRecorder
}

// MockFundTransferMockRecorder is the mock recorder for MockFundTransfer.
type MockFundTransferMockRecorder struct {
	mock *MockFundTransfer
}

// NewMockFundTransfer creates a new mock instance.
func NewMockFundTransfer(ctrl *gomock.Controller) *MockFundTransfer {
	mock := &MockFundTransfer{ctrl: ctrl}
	mock.recorder = &MockFundTransferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundTransfer) EXPECT() *MockFundTransferMockRecorder {
	return m.recorder
}

// Transfer mocks base method.
func (m *MockFundTransfer) Transfer(ctx context.Context, from, to exchange.AccountType, currency string, amount decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, from, to, currency, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer.
func (mr *MockFundTransferMockRecorder) Transfer(ctx, from, to, currency, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockFundTransfer)(nil).Transfer), ctx, from, to, currency, amount)
}
